kraken:
    distribution: openshift                                # Distribution can be kubernetes or openshift.
    kubeconfig_path: ~/.kube/config                        # Path to kubeconfig.
    exit_on_failure: False                                 # Exit when a post action scenario fails.
    litmus_version: v1.13.6                                # Litmus version to install.
    litmus_uninstall: False                                # If you want to uninstall litmus if failure.
    chaos_scenarios:                                       # List of policies/chaos scenarios to load.
        -   $scenario_type:                                # List of chaos pod scenarios to load.
            - $scenario_file
              $post_config
cerberus:
    cerberus_enabled: False                                # Enable it when cerberus is previously installed.
    cerberus_url:                                          # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal.

performance_monitoring:
    deploy_dashboards: False                               # Install a mutable grafana and load the performance dashboards. Enable this only when running on OpenShift.
    repo: "https://github.com/cloud-bulldozer/performance-dashboards.git"
    kube_burner_binary_url: "https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-x86_64.tar.gz"
    capture_metrics: False
    config_path: config/kube_burner.yaml                   # Define the Elasticsearch url and index name in this config.
    metrics_profile_path: config/metrics-aggregated.yaml
    prometheus_url:                                        # The prometheus url/route is automatically obtained in case of OpenShift, please set it when the distribution is Kubernetes.
    prometheus_bearer_token:                               # The bearer token is automatically obtained in case of OpenShift, please set it when the distribution is Kubernetes. This is needed to authenticate with prometheus.
    uuid:                                                  # uuid for the run is generated by default if not set.
    enable_alerts: False                                   # Runs the queries specified in the alert profile and displays the info or exits 1 when severity=error.
    alert_profile: config/alerts                           # Path to alert profile with the prometheus queries.

tunings:
    wait_duration: 6                                       # Duration to wait between each chaos scenario.
    iterations: 1                                          # Number of times to execute the scenarios.
    daemon_mode: False                                     # Iterations are set to infinity which means that the kraken will cause chaos forever.
