kraken:
    distribution: openshift                                # Distribution can be kubernetes or openshift
    kubeconfig_path: ~/.kube/config                        # Path to kubeconfig
    exit_on_failure: False                                 # Exit when a post action scenario fails
    port: 8081
    publish_kraken_status: True                            # Can be accessed at http://0.0.0.0:8081
    signal_state: RUN                                      # Will wait for the RUN signal when set to PAUSE before running the scenarios, refer docs/signal.md for more details
    litmus_install: True                                   # Installs specified version, set to False if it's already setup
    litmus_version: v1.13.6                                # Litmus version to install
    litmus_uninstall: False                                # If you want to uninstall litmus if failure
    litmus_uninstall_before_run: True                      # If you want to uninstall litmus before a new run starts
    chaos_scenarios:                                       # List of policies/chaos scenarios to load
        -   container_scenarios:                                 # List of chaos pod scenarios to load
            - -    scenarios/openshift/container_etcd.yml
        -   plugin_scenarios:
            - scenarios/openshift/etcd.yml
            - scenarios/openshift/regex_openshift_pod_kill.yml
            - scenarios/openshift/vmware_node_scenarios.yml
            - scenarios/openshift/network_chaos_ingress.yml
        -   node_scenarios:                                # List of chaos node scenarios to load
            -   scenarios/openshift/node_scenarios_example.yml
        -   plugin_scenarios:
            - scenarios/openshift/openshift-apiserver.yml
            - scenarios/openshift/openshift-kube-apiserver.yml
        -   time_scenarios:                                # List of chaos time scenarios to load
            - scenarios/openshift/time_scenarios_example.yml
        -   litmus_scenarios:                              # List of litmus scenarios to load
            - - scenarios/openshift/templates/litmus-rbac.yaml
              - scenarios/openshift/node_cpu_hog_engine.yaml
            - - scenarios/openshift/templates/litmus-rbac.yaml
              - scenarios/openshift/node_mem_engine.yaml
            - - scenarios/openshift/templates/litmus-rbac.yaml
              - scenarios/openshift/node_io_engine.yaml
        -   cluster_shut_down_scenarios:
            - - scenarios/openshift/cluster_shut_down_scenario.yml
              - scenarios/openshift/post_action_shut_down.py
        -   namespace_scenarios:
             - - scenarios/openshift/regex_namespace.yaml
             - - scenarios/openshift/ingress_namespace.yaml
               - scenarios/openshift/post_action_namespace.py
        -   zone_outages:
            - scenarios/openshift/zone_outage.yaml
        -   application_outages:
            - scenarios/openshift/app_outage.yaml
        -   pvc_scenarios:
            - scenarios/openshift/pvc_scenario.yaml
        -   network_chaos:
            - scenarios/openshift/network_chaos.yaml

cerberus:
    cerberus_enabled: False                                # Enable it when cerberus is previously installed
    cerberus_url:                                          # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal
    check_applicaton_routes: False                         # When enabled will look for application unavailability using the routes specified in the cerberus config and fails the run

performance_monitoring:
    deploy_dashboards: False                              # Install a mutable grafana and load the performance dashboards. Enable this only when running on OpenShift
    repo: "https://github.com/cloud-bulldozer/performance-dashboards.git"
    kube_burner_binary_url: "https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-x86_64.tar.gz"
    capture_metrics: False
    config_path: config/kube_burner.yaml                  # Define the Elasticsearch url and index name in this config
    metrics_profile_path: config/metrics-aggregated.yaml
    prometheus_url:                                       # The prometheus url/route is automatically obtained in case of OpenShift, please set it when the distribution is Kubernetes.
    prometheus_bearer_token:                              # The bearer token is automatically obtained in case of OpenShift, please set it when the distribution is Kubernetes. This is needed to authenticate with prometheus.
    uuid:                                                 # uuid for the run is generated by default if not set
    enable_alerts: False                                  # Runs the queries specified in the alert profile and displays the info or exits 1 when severity=error
    alert_profile: config/alerts                          # Path to alert profile with the prometheus queries

tunings:
    wait_duration: 60                                      # Duration to wait between each chaos scenario
    iterations: 1                                          # Number of times to execute the scenarios
    daemon_mode: False                                     # Iterations are set to infinity which means that the kraken will cause chaos forever
